readme.md
`perl-FindBin` is required to configure the `openssl` used by attestation library.
Fix: https://github.com/intel/MigTD/issues/17
=> readme: add build dependencies for CentOS Stream 9

Cargo.lock, deps/patches/rustls.diff, sh_script/preparation.sh, src/crypto/src/rustls_impl/tls.rs, src/std-support/rust-std-stub/src/lib.rs, src/std-support/rust-std-stub/src/prelude.rs, src/std-support/rust-std-stub/src/time.rs, src/std-support/sys_time/Cargo.toml
The latest `async-rustls` relies on rustls `0.21` codebase. If we want to utilize this crate, we need to update the `rustls` submiodule.
However, due to a `no_std` issue that has just been fixed in `rustls-webpki`, we have to use the latest `rustls` main branch. We can switch to a release tag once it has a new release.
=> Upgrade rustls

config/policy.json
MRTD and RTMRs need to be verified while checking MigTD policy.
Fix: https://github.com/intel/MigTD/issues/23
=> config: complete the content of the default policy

src/migtd/src/mig_policy.rs, src/migtd/src/ratls.rs, src/policy/src/config.rs, src/policy/src/verify.rs
When the operation of a property in policy is greater or equal and the reference value if `self`, we should compare between dst and src, otherwise the only qualified value will be equal to `self`.
Since MigTD-dst always start a TLS server and MigTD-src always start a TLS client, we can distinguish between migtd-s and d in this way when verifying the policy.
Fix: https://github.com/intel/MigTD/issues/22
=> policy: compare dst and src when op is greater_or_equal

.github/workflows/main.yml
=> Optimize main workflow in ci

deps/patches/rustls.diff
Fixed the version of webpki because fuzz crates have no Cargo.lock file.
=> deps: affix webpki version

src/devices/vsock/src/transport/virtio_pci.rs, src/devices/vsock/src/transport/vmcall.rs
The input vsock packets are untrusted and they should be checked before they can be used.
We can check its length or use the `new_checked` method to make sure the read/write on the slice won't panic.
Fix: https://github.com/intel/MigTD/issues/36
=> devices/vsock: check the packet length before use

readme.md
Document the requirement for the `GetQuote` and `SetupEventNotifyInterrupt` of remote attestation.
Resolve https://github.com/intel/MigTD/issues/39
=> readme: document the TDVMCALL leaves required by getting quote

config/policy.json
Migration from a lower SVN source to a higher SVN destination is allowed. This is conflict with the policy that requires `mrseam` to be equal.
=> config: remove `mrseam` from default policy

src/devices/pci/src/config.rs, src/devices/pci/src/lib.rs, src/devices/pci/src/mmio.rs
Fix https://github.com/intel/MigTD/issues/45
=> Fix the potential panics in crate `pci`

src/devices/virtio_serial/src/lib.rs, src/devices/vsock/src/transport/virtio_pci.rs
Calls of `pop_uses()` and `add()` method of `VirtQueue` may get error result. These errors should be correctly handled rather than unwrapped.
=> devices: remove unwraps that may cause panic

.github/workflows/fuzz.yml
Setting AFL_NO_AFFINITY disables attempts to bind to a specific CPU core on Linux systems.
Fix: https://github.com/intel/MigTD/issues/62
=> CI: set `AFL_NO_AFFINITY` to fix random fuzz failure

readme.md
Fix https://github.com/intel/MigTD/issues/54
=> Resolve the redundant tls packet issue

.github/workflows/fuzz.yml, rust-toolchain
Dependabot can't parse the rust-toolchain with legacy foramt.
=> use `TOML` encoding for `rust-toolchain` file

container/Dockerfile, readme.md, sh_script/docker.sh
The reproducible build of MigTD binary requires same user and code path, so we provide a `Dockerfile` for reproducibility.
Fix: https://github.com/intel/MigTD/issues/51
=> use docker for reproducible build

config/metadata.json
Payload binary should be marked as `Payload` metadata section and measured by td-shim into RTMR.
Closes https://github.com/intel/MigTD/issues/74
=> config: use `Payload` metadata section

sh_script/integration_tdx.sh
=> Kill migration td with vsock port message

config/metadata.json, config/policy.json, src/policy/src/verify.rs, src/policy/test/policy_003.json, src/policy/test/policy_006.json, src/policy/test/policy_full2.json, src/policy/test/policy_invalid_guid.json
Change the attribute value of `payload` section to `1`.
Closes https://github.com/intel/MigTD/issues/84
=> config: measure the `payload` section to mrtd

Cargo.lock, Cargo.toml, tools/migtd-hash/Cargo.toml, tools/migtd-hash/src/lib.rs, tools/migtd-hash/src/main.rs, xtask/src/servtd_info_hash.rs
`sertd-hash` is used to calculate `TEE_INFO_HASH` of migtd using migtd image and configuration manifest.
`td-shim/td-shim-tools` is used to calculate mrtd and rtmr[0-1] and extended to calculate the rtmr2 which is used by migtd.
Closes https://github.com/intel/MigTD/issues/86
=> tools: introduce `servtd-hash`

Cargo.lock, deps/patches/rustls.diff
Crates `env_logger` and `clap` are upgraded to remove the dependency `atty`.
=> deps: upgrade td-shim to close the security alert

config/policy_production_fmspc.json
Use array instead of string for reference of `sgxtcbcomponents`and `tdxtcbcomponents`.
Fix: https://github.com/intel/MigTD/issues/118
=> config: fix format of `policy_production_fmspc.json`

src/migtd/src/migration/mod.rs, src/migtd/src/ratls.rs
Closes: https://github.com/intel/MigTD/issues/114
=> migtd: add error status for invalid policy

src/devices/virtio_serial/src/port.rs
Fixes: https://github.com/intel/MigTD/issues/141
=> Fix invalid return length in `virtio-serial`

sh_script/build_final.sh, sh_script/test/integration_test.py, src/policy/test/policy.md, src/policy/test/policy_007.json, src/policy/test/policy_008.json, src/policy/test/policy_009.json, src/policy/test/policy_010.json
=> Test: Add more negative test cases in CI

.github/workflows/format.yml, .github/workflows/fuzz.yml, .github/workflows/integration-tdx.yml, .github/workflows/library.yml, .github/workflows/main.yml, Cargo.lock, container/Dockerfile, readme.md, rust-toolchain, src/devices/pci/src/lib.rs, src/devices/vsock/src/transport/event.rs, src/migtd/Cargo.toml, src/migtd/src/migration/data.rs, tests/test-td-payload/Cargo.toml
Fix the `AFL` issue:
```
error[E0599]: no function or associated item named `from_encoded_bytes_unchecked` found for struct `OsStr` in the current scope
Error:    --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_lex-0.7.0/src/ext.rs:282:16
|
282 |         OsStr::from_encoded_bytes_unchecked(second),
|                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `OsStr`
For more information about this error, try `rustc --explain E0599`.
```
=> upgrade rust nightly version

src/migtd/src/migration/session.rs
MigTD-s and MigTD-d exchange their MSK together with the version information and then they will evaluate the versions.
If there are one or more versions that meet both requirements, they will set the maximum one, otherwise the pre-migration flow will abort.
Closes https://github.com/intel/MigTD/issues/103
=> migtd: set `MIG_VERSION` before programming MSK

sh_script/test/mig-td.sh, sh_script/test/user-td.sh
This PR used to support v8.0+ qemu
```
The v8.1 qemu uses different command line arguments:
-object memory-backend-memfd-private,id=ram1,size=${mem} \
-machine q35,kernel_irqchip=split,memory-encryption=tdx,memory-backend=ram1 \
Changes to:
-object memory-backend-ram,id=mem0,size=${mem},private=on \
-machine q35,kernel_irqchip=split,memory-encryption=tdx,memory-backend=mem0 \
```
=> Update script to support v8.0+ QEMU

src/migtd/Cargo.toml, src/migtd/src/bin/migtd/main.rs, src/migtd/src/ratls.rs, xtask/src/build.rs
Closes https://github.com/intel/MigTD/issues/182
=> Add log level option at compile time

.github/workflows/main.yml, config/image_layout.json, config/metadata.json, src/migtd/src/config.rs, xtask/src/build.rs
- Adjust the image layout to make enough space for `Payload`
- Add debug migtd build job in CI
=> Fix debug migtd image build

Cargo.lock, src/attestation/build.rs, src/attestation/src/attest.rs, src/attestation/src/binding.rs, src/attestation/src/ghci.rs, src/crypto/src/x509.rs, src/devices/pci/src/config.rs, src/devices/virtio_serial/src/event.rs, src/devices/virtio_serial/src/lib.rs, src/devices/virtio_serial/src/port.rs, src/migtd/Cargo.toml, src/migtd/src/migration/session.rs, src/policy/Cargo.toml, src/policy/src/lib.rs, src/policy/src/verify.rs
Warning types:
- the Err-variant returned from this function is very large
- unused import
- use of a fallible conversion when an infallible one could be used
- the borrowed expression implements the required traits
- all variants have the same prefix
- comparing with null is better expressed by the .is_null() method
- casting to the same type is unnecessary
- this expression creates a reference which is immediately dereferenced by the compiler
- this impl can be derived
=> Close warnings reported by Clippy

Cargo.lock, src/devices/vsock/Cargo.toml, src/devices/vsock/src/transport/vmcall.rs, src/migtd/Cargo.toml, src/migtd/src/config.rs, src/migtd/src/event_log.rs, src/migtd/src/migration/session.rs, src/policy/Cargo.toml, src/policy/src/config.rs, tests/test-td-payload/Cargo.toml, tests/test-td-payload/src/main.rs, tests/test-td-payload/src/testattestation.rs, tools/migtd-hash/Cargo.toml, tools/migtd-hash/src/lib.rs
Closes: https://github.com/intel/MigTD/issues/87
=> upgrade td-shim submodule and use the shared memory shadow provided by `td-payload`

config/policy_pre_production_fmspc.json, src/policy/src/config.rs, src/policy/src/verify.rs, src/policy/test/policy_full1.json, tools/migtd-policy-generator/src/platform_tcb/mod.rs, tools/migtd-policy-generator/src/platform_tcb/tcb_info.rs, tools/migtd-policy-generator/src/policy.rs
`migtd-policy-generator` fetch the `tcbInfo` of all the platforms from backend server and enumerate all the possible `tdxModuleIdentities`.
Closes: https://github.com/intel/MigTD/issues/193
=> Support multiple TDX Module identities

src/policy/src/verify.rs
MigTD may have different features on different platforms. Mask the attribute and xfam bits that is not required for migtd.
=> migtd: mask the `xfam` and `attribute`

src/policy/src/config.rs
=> policy: Use size_of::<usize>() to get usize length

src/crypto/src/rustls_impl/ecdsa.rs
=> Remove casting a pointer to a u64 in sensitive_data_cleanup()

src/devices/virtio_serial/src/lib.rs, src/devices/vsock/src/lib.rs, src/devices/vsock/src/stream.rs
=> Fix potential dealock for register_serial_device and register_vsock_device

src/devices/virtio_serial/src/lib.rs
Potential underflow if `h2g.len()` is greater than the value in `receive_queues_prefill`.
Fixes https://github.com/intel/MigTD/issues/239
=> virtio_serial: check the host to guest buffer nums

src/devices/vsock/src/transport/vmcall.rs
To parse the packet header from raw bytes, the data fields needs to be validated before they can be used.
Closes https://github.com/intel/MigTD/issues/240
=> vsock: use `new_checked` to validate the untrusted packet

src/devices/virtio/src/virtio_pci.rs
Closes https://github.com/intel/MigTD/issues/205
=> virtio: fix potential out of bounds of array access

src/std-support/rust-std-stub/src/time.rs
Fixes https://github.com/intel/MigTD/issues/210
=> std-support: fix potential underflow in `duration_since`

src/devices/virtio/src/mem.rs
The write function should not take a &self reference since it modifies the memory region. It should take a &mut self reference to ensure that the mutable aliasing rules are respected.
Closes: https://github.com/intel/MigTD/issues/237
=> virtio: take mut reference for write methods

src/devices/virtio_serial/src/lib.rs, src/devices/vsock/src/transport/virtio_pci.rs
The while loop may stuck if device sends notification but there is no actual available buffer in the ring.
Closes https://github.com/intel/MigTD/issues/238
=> virtio: add timeout check waiting for virtqueue event

src/std-support/sys_time/src/lib.rs, src/std-support/sys_time/src/rtc.rs
For the rtc device, it is possible to read the time and date while an update is in progress and get inconsistent values.
We retry for up to 500 times for the RTC to be ready which takes about 100ms.
Closes https://github.com/intel/MigTD/issues/208
=> sys_time: limit the number of retries for reading rtc time

readme.md
Closes: https://github.com/intel/MigTD/issues/246
Closes: https://github.com/intel/MigTD/issues/247
=> readme: add description about the connection timeout

Cargo.lock, src/policy/Cargo.toml, src/policy/src/config.rs
The family of lexical crates have a variety of unresolved safety issues and no activity in the last two years. Considering we're only using it in two places, it makes morse sense to just use the built in conversion for usize and reduce the number of dependencies.
=> Remove dependency on lexical crates.

src/crypto/fuzz/Cargo.toml, src/devices/virtio/fuzz/Cargo.toml, src/devices/vsock/fuzz/Cargo.toml, src/migtd/fuzz/Cargo.toml, src/policy/fuzz/Cargo.toml
Since the compiler of oss-fuzz is not the latest version, so it will meet build failure for crate "serde 1.0.204". So we use a fixed version serde "1.0.198" to fix the issue.
=> Fix oss-fuzz build failure issue

src/devices/virtio/src/virtio_pci.rs
The MSI-X table offset is supposed to have the BIR bits masked off. PCI Spec V3.0 6.8.2.4: "The lower 3 Table BIR bits are masked off (set to zero) by software to form a 32-bit QWORD-aligned offset".
=> Fix MSI-X table offset by masking off the BIR bits

Cargo.lock, src/std-support/rust-std-stub/Cargo.toml
Yanked version of `ahash` is used by hashbrown, fix this by upgrading hashbrown to latest.
=> std-support: upgrade `hashbrown`

Cargo.lock, src/attestation/src/attest.rs, src/crypto/Cargo.toml, src/crypto/src/lib.rs, src/migtd/Cargo.toml
Closes https://github.com/intel/MigTD/issues/287
=> remove unused functions in `attestation` and `crypto`

src/devices/vsock/src/stream.rs
`buf_alloc` and `fwd_cnt` in packet header are used for buffer space management of stream sockets. If peer has insufficient buffer space, the sender waits until new packets are returned and checks `buf_alloc` and `fwd_cnt` again.
`VIRTIO_VSOCK_OP_CREDIT_REQUEST` packet is used to query how much buffer space is available. `VIRTIO_VSOCK_OP_CREDIT_UPDATE` replies the query and it can also be sent without previous request.
This patch tracks the `fwd_cnt` and `buf_alloc` to calculate the free space of peer. The credite request and update packets are also handled.
=> vsock: add buffer space management

src/devices/virtio_serial/src/lib.rs, src/devices/virtio_serial/src/port.rs, src/devices/vsock/src/stream.rs
After receiving from vsock/virtio-serial transport layer, pop all the data packet from device and try to fill the caller's buffer as much as possible.
=> vsock/virtio-serial: pop all the received packets

Cargo.lock, src/crypto/Cargo.toml
This version contains fix of the TLS handshake deframing issue.
Closes https://github.com/intel/MigTD/issues/305
=> crypto: upgrade rustls to 0.23.20

readme.md
Closes https://github.com/intel/MigTD/issues/201
=> readme: add migration error codes and their causes

src/devices/vsock/Cargo.toml, tools/migtd-hash/Cargo.toml
There are some manifest warnings due to "unused manifest key" because of misspelled keywords. This change addresses those warnings.
=> Fix cargo build warnings.

Cargo.lock, config/mmio_layout.json, src/devices/pci/Cargo.toml, src/devices/pci/src/config.rs, src/devices/pci/src/layout.rs, src/devices/pci/src/lib.rs, src/devices/pci/src/mmio.rs, src/migtd/src/driver/serial.rs, src/migtd/src/driver/vsock.rs, src/migtd/src/lib.rs, xtask/Cargo.toml, xtask/src/build.rs, xtask/src/config.rs, xtask/src/main.rs
The new configuration file contains the address and size of MMIO space and PCIE config space.
Closes https://github.com/intel/MigTD/issues/115
=> config: add MMIO layout

src/devices/vsock/src/transport/vmcall.rs
Unlike virtio-vsock, the can_recv method of vmcall-vsock should return false because each recv operation depends on a vmcall.
=> vmcall-vsock: always return false in `can_recv`

src/attestation/build.rs
The result from running a command only indicates whether it was able to spawn and does not check whether it finished successfully. This change is to check whether the exit status was successful so `make` failures are not silently ignored.
Signed-off-by: David Skidmore <davidskidmore@google.com>
=> Check exit status of build script commands.

container/Dockerfile
Docker file specifies old nightly toolchain which is being overwritten by rust-toolchain anyway.
Add missing x86_64-unknown-none target.
After these changes the docker image is ready for building.
Add python, pip, and pytest into container.
=> Fix rust toolchain and add pytest to docker

src/devices/vsock/src/stream.rs, src/devices/vsock/src/transport/virtio_pci.rs, src/devices/vsock/src/transport/vmcall.rs
Closes https://github.com/intel/MigTD/issues/452
Closes https://github.com/intel/MigTD/issues/453
=> vsock: fix issues with large chunk transmission
