intel/MigTD

.github/workflows/deny.yml
.github/workflows/format.yml
.github/workflows/fuzz.yml
.github/workflows/integration-tdx.yml
.github/workflows/library.yml
sh_script/build_final.sh
sh_script/fuzzing.sh

1: Move deny check from main to deny.yml
2: Move clippy and format check from main to format.yml
3. Update fuzz.yml
4. Update integration-tdx.yml
5. Fix fuzzing test script

Adjust and enabling CI tasks

---

Cargo.lock
config/shim_layout.json
sh_script/build_final.sh
src/migtd/src/lib.rs
xtask/src/build.rs
xtask/src/main.rs
xtask/src/servtd_info_hash.rs

Fix: https://github.com/intel/MigTD/issues/11

update td-shim and related build scripts

---

Cargo.lock
config/metadata.json

Fix: https://github.com/intel/MigTD/issues/13

Correct the attribute of `PermMem` metadata section and update `td-shim`

---

.github/workflows/integration-tdx.yml
.github/workflows/main.yml
Cargo.lock
Cargo.toml
readme.md
sh_script/build_final.sh
sh_script/integration_tdx.sh
src/devices/pci/src/config.rs
src/devices/virtio/src/consts.rs
src/devices/virtio/src/lib.rs
src/devices/virtio/src/virtio_pci.rs
src/devices/virtio/src/virtqueue.rs
src/devices/virtio_serial/Cargo.toml
src/devices/virtio_serial/src/event.rs
src/devices/virtio_serial/src/lib.rs
src/devices/virtio_serial/src/port.rs
src/devices/vsock/src/transport/virtio_pci.rs
src/migtd/Cargo.toml
src/migtd/src/driver/mod.rs
src/migtd/src/driver/serial.rs
src/migtd/src/lib.rs
src/migtd/src/migration/mod.rs
src/migtd/src/migration/session.rs

Fix: https://github.com/intel/MigTD/issues/9

Add virtio serial support

---

.github/workflows/integration-tdx.yml
sh_script/build_final.sh
sh_script/integration_tdx.sh
src/policy/test/policy.md
src/policy/test/policy_006.json

Fix #28 
Add 3 new tcs to test op “greater-or-equal”
Update test script to more flexible
Update CI tasks

Update integration test

---

readme.md

Upgrade to tag [sgx_2.21](https://github.com/intel/linux-sgx/tree/sgx_2.21)

deps: upgrade `linux-sgx` submodule

---

config/policy.json

To make the svn trackable.
Fix: https://github.com/intel/MigTD/issues/56

config: require the values of svn seam to be same

---

Cargo.lock

Fix: https://github.com/intel/MigTD/issues/66

udpate Cargo.lock

---

src/crypto/src/rustls_impl/tls.rs
src/devices/virtio/src/mem.rs
src/devices/vsock/src/stream.rs
src/migtd/src/event_log.rs
src/migtd/src/migration/session.rs
src/migtd/src/ratls.rs
src/policy/src/verify.rs

Change the warning via clippy scan #64

Cargo Clippy Warning

---

src/migtd/src/mig_policy.rs
src/migtd/src/ratls.rs
src/policy/src/lib.rs
src/policy/src/verify.rs

For better handling of errors.

policy: use Result enum instead of bool

---

Cargo.lock
deps/patches/rustls.diff
sh_script/preparation.sh
src/attestation/src/ghci.rs
src/crypto/Cargo.toml
src/crypto/src/rustls_impl/ecdsa.rs
src/crypto/src/rustls_impl/tls.rs
src/migtd/src/bin/migtd/main.rs
src/migtd/src/driver/serial.rs
src/migtd/src/driver/vsock.rs
src/migtd/src/lib.rs
src/migtd/src/migration/session.rs
src/std-support/rust-std-stub/src/lib.rs
tests/test-td-payload/src/main.rs

Fixes https://github.com/intel/MigTD/issues/91

deps: upgrade td-shim and rustls

---

config/policy_with_fmspc.json
readme.md
xtask/src/build.rs

Closes https://github.com/intel/MigTD/issues/100

xtask: use config/policy_with_fmspc.json by default 

---

src/migtd/src/ratls.rs
src/policy/src/config.rs
src/policy/src/lib.rs
src/policy/src/verify.rs

Print out the policy error detail if policy check failed.
Closes: https://github.com/intel/MigTD/issues/123

policy: add detailed information in error results

---

src/devices/vsock/src/transport/vmcall.rs

Remove invalid loops

---

src/policy/src/config.rs
src/policy/src/lib.rs
src/policy/src/verify.rs

Closes: https://github.com/intel/MigTD/issues/136
Closes: https://github.com/intel/MigTD/issues/135

policy: fix several mistakes in comparing logic

---

src/policy/src/lib.rs
src/policy/src/verify.rs

Fix: https://github.com/intel/MigTD/issues/134

Policy: add `fmspc` information in error result

---

config/policy_pre_production_fmspc.json
config/policy_production_fmspc.json

Closes: https://github.com/intel/MigTD/issues/122

config: update policies with `migtd-policy-generator`

---

doc/security_test.md

Add security test document

---

readme.md

`migtd-attr` shall be set together with the `migtd-hash` in qemu `-object` subcommand.
Add scripts to show how to launch a user TD in pre-binding approach and how to do the actual binding.
Closes https://github.com/intel/MigTD/issues/148

readme: add `migtd-attr` and pre-binding introduction

---

src/attestation/build.rs

Closes https://github.com/intel/MigTD/issues/154

attestation: update to latest linux-sgx branch

---

.github/workflows/integration-tdx.yml
sh_script/build_final.sh
sh_script/test/conftest.py
sh_script/test/integration_test.py
sh_script/test/pre-mig.sh
sh_script/test/user-td.sh

Closes https://github.com/intel/MigTD/issues/151

CI: add integration test for `pre-binding`

---

Cargo.lock
src/migtd/Cargo.toml

Bump version to 0.4.0

---

.github/workflows/main.yml

Replaced the old build command with commands in readme.

CI: Update build commands in main.yml

---

config/policy_pre_production_fmspc.json

A new platform with fmspc "50A06F000000" is added.

config: update pre-production policy list

---

src/devices/virtio_serial/src/lib.rs

Fix incrorrect queue index in init_queues()

---

src/devices/vsock/src/lib.rs
src/devices/vsock/src/stream.rs

Remove unwrap() in devices/vsock/src/stream.rs

---

src/crypto/src/x509.rs

Remove unwrap from sign()

---

src/devices/pci/src/mmio.rs

Fix potential integer overflow in alloc_mmio32()

---

src/attestation/src/root_ca.rs

Remove unwrap() from set_ca()

---

readme.md

Closes https://github.com/intel/MigTD/issues/245

readme: add clarification about pre-prod and prod platform migration

---

.github/workflows/deny.yml
.github/workflows/trivy.yml

CI: Change schedule of cargo-deny and trivvy to daily run

---

Cargo.lock
Cargo.toml
src/devices/vmcall_raw/Cargo.toml
src/devices/vmcall_raw/src/lib.rs
src/devices/vmcall_raw/src/stream.rs
src/devices/vmcall_raw/src/transport/event.rs
src/devices/vmcall_raw/src/transport/mod.rs
src/devices/vmcall_raw/src/transport/vmcall.rs
src/migtd/Cargo.toml
src/migtd/src/bin/migtd/main.rs
src/migtd/src/driver/mod.rs
src/migtd/src/driver/vmcall_raw.rs
src/migtd/src/lib.rs
src/migtd/src/migration/data.rs
src/migtd/src/migration/event.rs
src/migtd/src/migration/session.rs

migtd: ghci 1.5 spec implementation
Signed-off-by: Mukesh Jagasia <mukesh.j.jagasia@intel.com>

migtd: ghci 1.5 spec implementation

---

src/migtd/src/migration/data.rs

Closes https://github.com/intel/MigTD/issues/385

migtd: do not parse socket info HOB when vsock is not used

---

src/devices/vmcall_raw/src/transport/vmcall.rs
src/migtd/src/migration/session.rs

Signed-off-by: Mukesh Jagasia mukesh.j.jagasia@intel.com

Fixing WFR as per GHCI 1.5 spec & status field extended to 8 bytes
